### ISSUE TITLE
sbin/iptables: command not found

### ISSUE THREAD

**Issue by zmweske** [Neomediatech/opencanary#1]
When viewing the docker logs, the following line is found about 12 consecutive times. 
```
sudo: /sbin/iptables: command not found
```
Additionally, this only appears when the portscan is enabled

**Comment by zmweske** [comment]
https://github.com/thinkst/opencanary/wiki#im-receiving-iptables-errors-on-debian-11

**Comment by feddar** [comment]
Thanks @zmweske , I just added iptables on [Dockerfile](../blob/master/Dockerfile). The new image is availabe with the command 'docker pull neomediatech/opencanary'.
